#pragma once

// Logging
#define BLAZAR_CONFIG_LOG_RESOURCE_USAGE
#define BLAZAR_ENABLE_ASSERTS
#define BLAZAR_IMGUI_ENABLED

// Development
#define BLAZAR_CFG_DEV_ENABLE
#define BLAZAR_CFG_DEV_RENDER_COMMAND_INTROSPECTION

// Configuration rules
#ifdef BLAZAR_DIST
#undef BLAZAR_ENABLE_ASSERTS
#endif